### ISSUE TITLE
phpBB matching failure

### ISSUE THREAD

**Issue by sxxs** [wichmannpas/webapp-version-inferer#1]
Example: http://www.narkolepsie.ch

wappalyzer detects correctly that this site uses phpBB

versioninferrer starts to try paths like http://www.narkolepsie.ch/phpBB/docs/CHANGELOG.html - however none of them can be retrieved.

However, http://www.narkolepsie.ch/docs/CHANGELOG.html can be retrieved just fine. Would be great to have more flexibility here so that this kind of small change does not prevent versioninferrer from working.

**Comment by wichmannpas** [comment]
This was caused by a wrong path mapping within the phpBB provider.
