### ISSUE TITLE
`analyze_site.py` should not write the full JSON output to stdout by default

### ISSUE THREAD

**Issue by muellermartin** [wichmannpas/webapp-version-inferer#5]
Currently the `analyze_site.py` script writes the full JSON output to stdout which can be a huge amount of text. Therefore the script should not print the JSON data by default.

I'd suggest to add an option like `--json` to enable this behaviour, e. g. when this flag is used the JSON gets printed as well, otherwise it will be suppressed.

I'm willing to provide a PR for this :)

**Comment by wichmannpas** [comment]
In fact, there is already a `--json-file` parameter that writes the output to a file instead of stdout. However, I agree that it would be a sensible default to not print the json output to stdout without an explicit argument. I would like to see a PR for that :)

**Comment by muellermartin** [comment]
As a temporary workaround the `--json-file` option can also be "misused" to omit the JSON output by simply using `/dev/null` as the output file, so it is quite useful even in this case ;)

PR is on the way :)

**Comment by wichmannpas** [comment]
> As a temporary workaround the `--json-file` option can also be "misused" to omit the JSON output by simply using `/dev/null` as the output file, so it is quite useful even in this case ;)

In fact, my shell history tells me that I have done exactly that several times in the past ^^
